<a href="https://colab.research.google.com/github/Prashantt21/Portfolio_Projects/blob/main/Numpy_Advanced_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center> Numpy Basics </center>

In [ ]:
#import numpy module with alias np

import numpy as np

We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [ ]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it

arr = np.array([1,2,3])

In [ ]:
# print output
arr


array([1, 2, 3])

## Dimensions in Arrays

Create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [ ]:
#define a,b,c and d as instructed above
a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])



Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [ ]:
#print dimentions of a,b, c and d
print("a:", a)
print("b:", b)
print("c:", c)
print("d:", d)




a: 10
b: [1 2 3]
c: [[1 2 3]
 [4 5 6]]
d: [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute



In [ ]:
# print shape of each a,b ,c and d

a.shape
b.shape
c.shape
d.shape



(2, 2, 3)

Lets check data type passed in our array. To check data type you can use dtype attribute

In [ ]:
# print data type of c and d
print(c.dtype)
print(d.dtype)

int64
int64


Above output mean our array is having int type elements in it.

Lets check the type of our variable. To check type of any numpy variable use type() function

In [ ]:
#print type of a and b variable
print(type(a))
print(type(b))





<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
# Lets check length of array b, using len() function
print(len(b))

3


Bravo!You have Defined ndarray i.e numpy array in variable a nd b. Also you have successfully learned how to create numpy.

Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [ ]:
# Define l1,l2,l3 and l4 as stated above.
l1 = [10,20,30]
l2 = [40,50,60]
l3 = np.array(l1)
l4 = np.array(l2)



Lets multiply each elements of l1 with corresponding elements of l2

Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line<br>
eg. %timeit my_code

In [ ]:
#code here as instructed above
%timeit [i*j for i,j in zip(l1,l2)]
%timeit np.multiply(l3,l4)

674 ns ± 3.61 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
865 ns ± 263 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [ ]:
%timeit [i*j for i,j in zip(l3,l4)]
%timeit np.multiply(l1,l2)



1.98 µs ± 364 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
3.91 µs ± 89.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Don't worry if still your one line of code is running. Its because your system is calculating total time taken to run your code.

Did you notice buddy! time taken to multiply two lists takes more time than multiplyimg two numpy array.
Hence proved that numpy arrays are faster than lists.

**Fun Fact time!:**

You know in many data science interviews it is asked that what is the difference between list and array.<br>


In [ ]:
#Create a numpy array using arange with 1 and 11 as parameter in it
import numpy as np

arr = np.arange(1,11)
print(arr)



[ 1  2  3  4  5  6  7  8  9 10]


This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [ ]:
# Create an array using arange passing 1,11 and 2 as parameter in iter
import numpy as np
arr = np.arange(1,11,2)
print(arr)

[1 3 5 7 9]


In [ ]:
# create numpy array using eye function with 3 as passed parameter
import numpy as np
identify_matrix = np.eye(3)
print(identify_matrix)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Using arange() to generate numpy array x with numbers between 1 to 16
import numpy as np
x = np.arange(1,16)
print(x)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
# Reshape x with 2 rows and 8 columns
x1 = np.array(x)
reshape_x = x1.reshape(2,6)
reshape_x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array


In [ ]:
# reshaoe x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:
x = np.arange(32)
reshape_x = x.reshape(2,2,4,2)
reshape_x


array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]]])

In [ ]:
# Use unknown dimention to reshape x into 2-D numpy array with shape 4*4
x = np.arange(16)
reshape_x = x.reshape(4,4)
reshape_x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# Use unknown dimention to  reshape x into 3-D numpy array with 2 arrays that contains 4 arrays
y = np.arange(32)
reshape_y = y.reshape(-1,2,4)
print(reshape_y.shape)
# print y



(4, 2, 4)


In [ ]:
# Flattening y

flatten_y = y.ravel()
flatten_y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [ ]:
# Create an array a with all even numbers between 1 to 17
a = np.arange(1, 18)[np.arange(1, 18) % 2 == 0]
print(a)
# print a


[ 2  4  6  8 10 12 14 16]


In [ ]:
# Get third element in array a
third_element = a[2]
third_element

6

In [ ]:
#Print 3rd, 5th, and 7th element in array a
selected_elements = a[[2, 4, 6]]
selected_elements


array([ 6, 10, 14])

Lets check the same for 2 D array

In [ ]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# print the 3rd element from the 3rd row of a
third_element = a[2, 2]
third_element

9

Well done!

Now lets check indexing for 3 D array

In [ ]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
b


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.
third_element = b[0, 1, 2]
third_element



6

In [ ]:
# Create 1D array

arr= np.array([1, 2, 3, 4, 5,6,7,8,9])

arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Slice elements from 1st to 5th element from the following array:
slice_elements = a[1:5]
slice_elements



array([[4, 5, 6],
       [7, 8, 9]])

Note: The result includes the start index, but excludes the end index.



In [ ]:
# Slice elements from index 5 to the end of the array:
slice_element1 = a[5:]
slice_element1


array([], shape=(0, 3), dtype=int64)

In [ ]:
# Slice elements from the beginning to index 5 (not included):
slice_element1 = a[:5]
slice_element1




array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**STEP**

Use the step value to determine the step of the slicing:

In [ ]:
# Print every other element from index 1 to index 7:
sliced_elements = arr[0:7]
sliced_elements



array([1, 2, 3, 4, 5, 6, 7])

Did you see? using step you were able to get alternate elements within specified index numbers.

In [ ]:
# Return every other element from the entire array arr:

every_other_element = arr[::2]
every_other_element

array([1, 3, 5, 7, 9])

well done!

Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here.

**Array slicing in 2-D array.**

In [ ]:
# Print array a

a = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
# From the third element, slice elements from index 1 to index 5 (not included) from array 'a'
sliced_elements = a[2][1:5]
sliced_elements



[8, 9]

In [ ]:
# In array 'a' print index 2 from all the elements :
element_at_index_2 = a[2]
element_at_index_2



[7, 8, 9]

In [ ]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:
sliced_a = a[1:]
sliced_a



[[4, 5, 6], [7, 8, 9]]

Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view

In [ ]:
x1= np.array([1,2,3,4,5,6])

x1

array([1, 2, 3, 4, 5, 6])

In [ ]:
# assign x2 = x1
x2 = x1


In [ ]:
#print x1 and x2
x1
x2



array([1, 2, 3, 4, 5, 6])

Ok now you have seen that both of them are same

In [ ]:
# change 1st element of x2 as 10
x2[0]=10
x2



array([10,  2,  3,  4,  5,  6])

In [ ]:
#Again print x1 and x2
x1
x2



array([10,  2,  3,  4,  5,  6])

In [ ]:
# Create a view of x1 and store it in x3.
x3 = x1.view()
x3
x1


array([10,  2,  3,  4,  5,  6])

In [ ]:
# Again check memory share between x1 and x3
memory_shared = np.shares_memory(x1, x3)

if memory_shared:
  print("x1 and x3 share memory.")
else:
  print("x1 and x3 do not share memory.")



x1 and x3 share memory.


Woh! simple assignment is similar to view. That means
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [ ]:
#Change 1st element of x3=100
x3[0] = 100
x1
x3


array([100,   2,   3,   4,   5,   6])

In [ ]:
#print x1 and x3 to check if changes reflected in both
x1
x3



array([100,   2,   3,   4,   5,   6])

Now its proved.

Lets see how **Copy()** function works

In [ ]:
# Now create an array x4 which is copy of x1

x4 = x1.copy()
x4



array([100,   2,   3,   4,   5,   6])

In [ ]:
# Change the last element of x4 as 900
x4[-1]= 900
x4




array([100,   2,   3,   4,   5, 900])

In [ ]:
# print both x1 and x4 to check if changes reflected in both
x4
x1




array([100,   2,   3,   4,   5,   6])

Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

Still not convinced? Ok lets see if they both share memory or not

In [ ]:
#Check memory share between x1 and x4
memory_shared = np.shares_memory(x1, x4)

if memory_shared:
  print("x1 and x4 share memory.")
else:
  print("x1 and x4 do not share memory.")



x1 and x4 do not share memory.


**hstack vs vstack function**


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function:

1. hstack() to stack along rows.
2. vstack()  to stack along columns

In [ ]:
# stack x1 and x4 along columns
stacked_array = np.hstack((x1,x4))
stacked_array

array([100,   2,   3,   4,   5,   6, 100,   2,   3,   4,   5, 900])

In [ ]:
#stack x1 and x4 along rows
stacked_array1 = np.vstack((x1,x4))
stacked_array1

array([[100,   2,   3,   4,   5,   6],
       [100,   2,   3,   4,   5, 900]])

We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

In [ ]:
 arr1 = np.array([1,2,3])


 arr2 = np.array([4,5,6])


##join arr1 and arr2 along rows using concatenate() function
concatenated_array = np.concatenate((arr1,arr2))
concatenated_array


array([1, 2, 3, 4, 5, 6])

In [ ]:
##join arr1 and arr2 along columns using concatenate() function
concatenated_array = np.concatenate((arr1,arr2), axis = 0)
concatenated_array


array([1, 2, 3, 4, 5, 6])

## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [ ]:
# append arr2 to arr1
appended_array = np.append(arr2,arr1)
appended_array


array([4, 5, 6, 1, 2, 3])

Lets use insert() function which Inserts values into array before specified index value

In [ ]:
# Inserts values into array x1 before index 4 with elements of x4
new_arr = np.insert(x1,4,[6,7])
new_arr

array([100,   2,   3,   4,   6,   7,   5,   6])

You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [ ]:
# delete 2nd element from array x2
new_arr = np.delete(x2, 2, axis=None)

new_arr

array([100,   2,   3,   4,   5,   6])

Did you see? 2 value is deleted from x2 which was at index position 2

Good Job learner!